# Generated by Django 5.2.9 on 2025-12-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('mark', models.IntegerField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('fantasy', 'Fantasy')], max_length=50)),
            ],
        ),
    ]
