# Generated by Django 5.2.9 on 2026-01-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(null=True, upload_to='films_images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
