# Generated by Django 5.2.9 on 2026-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_film_image_alter_film_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films_images/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
