# Generated by Django 5.2.9 on 2026-01-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_film_image_alter_film_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('fantasy', 'Fantasy'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('documentary', 'Documentary'), ('animation', 'Animation'), ('adventure', 'Adventure'), ('mystery', 'Mystery'), ('crime', 'Crime'), ('musical', 'Musical'), ('biography', 'Biography'), ('war', 'War'), ('western', 'Western')], max_length=50),
        ),
    ]
