# Generated by Django 5.2.9 on 2026-01-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_film_image_url_alter_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='films_videos/'),
        ),
    ]
